site_name: Rajaswa Patil
site_url: https://rajaswapatil.com
theme:
  name: material
  features:
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default 
      primary: black 
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - blog:
      blog_dir: notes
      authors: true
      authors_file: "{blog}/.authors.yml"
      authors_profiles: true
      authors_profiles_name: Authors
      authors_profiles_url_format: "author/{slug}"
      blog_toc: true
      categories_name: Topics
      categories_url_format: "category/{slug}"
      draft: false
      pagination: true
      pagination_per_page: 5
      pagination_url_format: "page/{page}"
      post_dir: "{blog}/posts"
      post_date_format: long
      post_readtime: true
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
  - search
extra:
  analytics:
    provider: google
    property: G-WKNC0Q3JDT
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:patilrajaswa@gmail.com
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/RajaswaPatil
    - icon: fontawesome/brands/github
      link: https://github.com/rajaswa
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/rajaswa-patil
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?user=79uJMXsAAAAJ
  generator: false
nav:
  - About:
    - Introduction: index.md
    - Experience: about/experience.md
  - Portfolio:
    - Product: portfolio/products.md
    - Research: portfolio/research.md
    - Open Source: portfolio/open-source.md
  - Work With Me:
    - Consulting Services: work-with-me/consulting.md
    - Testimonials: work-with-me/testimonials.md
    - Endorsements: work-with-me/endorsements.md
  - Notebook:
    - notes/index.md
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: Copyright &copy; Rajaswa Patil 2024