authors:
  rajaswa:
    name: Rajaswa Patil
    description: Applied AI Consultant.
    avatar: https://avatars.githubusercontent.com/u/34607601?v=4
    slug: rajaswa-patil
    url: https://twitter.com/intent/follow?screen_name=RajaswaPatil